#!/usr/bin/env bash
# Configures a new Ubuntu server with a HAproxy load-balancer
sudo apt-get -y update
sudo apt-get -y install haproxy
echo "
frontend web-frontend
	bind *:80
	default_backend web-backend
backend web-backend
	balance roundrobin
	server 139608-web-01 52.87.216.236:80 check
	server 139608-web-02 100.26.171.103:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg

# Enable HAProxy management
sudo sed -i 's/ENABLED=0/ENABLED=1/g' /etc/default/haproxy

sudo service haproxy restart
