#!/usr/bin/env bash
# display Best School 10 times using while loop
((a = 0))

while ((a < 10))
do
	if ((a == 3))
then
	echo bad luck
elif ((a == 7))
then
	echo good luck
else
	echo Best School
fi
	((a++))	
done
