#!/usr/bin/env bash
# display Best School 10 times using while loop
((a = 1))

while ((a < 21))
do
	echo $a
case $a  in
	"4")
		echo "bad luck from China"
		;;
	"9")
		echo "bad luck from Japan"
		;;
	"17")
		echo "bad luck from Italy"
esac
((a++))
done
